name: stac-tests

on:
  pull_request:
  push:
    branches:
      - "main"
      - "develop"
      - "feat/stac-prod-crunch"
  workflow_call:

jobs:
  check-pre-commit-hooks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files --verbose

  test-stac-validity:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Run tests
        run: pytest
